version: '3'
services:
  python3:
    restart: always
    build:
      context: .
      args:
        REPO_ROOT_DIR: '/usr/local/src/Japanese-Company-Lexicon'
        USR_DIC_DIR: '/var/lib/mecab/dic/user_dict'
    container_name: 'python3-test'
    working_dir: '/usr/local/src/'
    tty: true
    environment:
      MECABRC: '/etc/mecabrc'
    volumes:
      - ./work:/usr/local/src/work
