version: '3'
services:
  api:
    restart: always
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: 'api-test'
    working_dir: '/usr/local/src/'
    tty: true
    volumes:
      - ./work:/usr/local/src/work
    command: aglio --theme-variables slate -i work/md/index.md -s -h 0.0.0.0
